#!/bin/bash
set -e

cd $(dirname $0)/..

source ./scripts/version

if [ "${KERNEL_ARCH}" != "loongarch" ]; then
    ./scripts/test-firmware
fi

if ! ./scripts/download; then
    echo "blah"
    exit 1
fi
./scripts/extract
run-parts -v ./scripts/hooks
./scripts/build-kernel
./scripts/package-kernel
./scripts/build-images

